import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import AppMenu from "./components/menu";
import AppFooter from "./components/footer";
import ChatBox from "./components/ChatBox";
import { AppProvider } from "../contexts"; // 👉 Cập nhật import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isAdminPage = false;
  if (typeof window !== 'undefined') {
    isAdminPage = window.location.pathname.startsWith('/admin');
  } else if (typeof document !== 'undefined') {
    isAdminPage = document.location.pathname.startsWith('/admin');
  }
  return isAdminPage ? (
    <html lang="vi" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  ) : (
    <html lang="vi" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppProvider>
          <AppMenu />
          {children}
          <AppFooter />
          <ChatBox />
        </AppProvider>
      </body>
    </html>
  );
}